name: 'AI Reviewer'
description: 'Composite GitHub Action to set up Python and run a Python script'
inputs:
  python_version:
    description: 'The Python version to use'
    required: false
    default: '3.x'
runs:
  using: 'composite'
  steps:
    # Step 1: Check if Python is already set up. If not, set it up.
    - name: Check if Python is set up
      shell: bash
      id: check-python
      run: |
        if ! command -v python &> /dev/null; then
          echo "Python is not installed"
          echo "python_setup=false" >> $GITHUB_ENV
        else
          echo "Python is already installed"
          echo "python_setup=true" >> $GITHUB_ENV
        fi

    # Step 2: Set up Python if not already set up
    - name: Set up Python
      if: env.python_setup != 'true'
      uses: actions/setup-python@v2
      with:
        python-version: ${{ inputs.python_version }}

    # Step 3: Install dependencies (optional)
    - name: Install dependencies
      shell: bash
      run: |
        if [ -f requirements.txt ]; then
          pip install -r requirements.txt
        fi

    # Step 4: Get the repository name from GitHub context
    - name: Get Repository Info
      shell: bash
      run: |
        REPO_NAME=$(echo $GITHUB_REPOSITORY | cut -d '/' -f2)
        PR_NUMBER=${{ github.event.pull_request.number }}

        echo "REPO_NAME=$REPO_NAME" >> $GITHUB_ENV
        echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_ENV

        echo "Repository Name: $REPO_NAME"
        echo "Pull Request Number: $PR_NUMBER"

    # Step 6: Run the Python script
    - name: Run Python script
      shell: bash
      run: |
        python3 main.py 
   
