name: 'AI Reviewer'
description: 'Composite GitHub Action to set up Python and run a Python script'
inputs:
  python_version:
    description: 'The Python version to use'
    required: false
    default: '3.x'
  github_token:
    description: ""
    required: true
runs:
  using: 'composite'
  steps:
    - name: Get Repository Info
      shell: bash
      run: |
        GITHUB_REPO=$GITHUB_REPOSITORY
        GITHUB_PR_NUMBER=${{ github.event.pull_request.number }}
        GITHUB_TOKEN=${{ inputs.github_token }}
        echo "GITHUB_REPO=$GITHUB_REPO" >> $GITHUB_ENV
        echo "GITHUB_PR_NUMBER=$GITHUB_PR_NUMBER" >> $GITHUB_ENV
        echo "GITHUB_TOKEN=$GITHUB_TOKEN" >> $GITHUB_ENV

        echo "Github Repo: $GITHUB_REPO"
        echo "Gituh PR Number: $GITHUB_PR_NUMBER"

    # Step 6: Run the Python script
    - name: Run Python script
      shell: bash
      run: | 
        cd ${{ github.action_path }}
        pip install -r requirements.txt
        python3 main.py
